# Generated by Django 2.0.1 on 2018-08-03 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('question', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('answer', models.CharField(max_length=250)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('styling_goal', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('testimonial', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
